/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComoFuncionaRouteImport } from './routes/como-funciona'
import { Route as EntregadoresRouteImport } from './routes/entregadores'
import { Route as EstabelecimentosRouteImport } from './routes/estabelecimentos'
import { Route as SuporteRouteImport } from './routes/suporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoFuncionaRoute = ComoFuncionaRouteImport.update({
  id: '/como-funciona',
  path: '/como-funciona',
  getParentRoute: () => rootRouteImport,
} as any)
const EntregadoresRoute = EntregadoresRouteImport.update({
  id: '/entregadores',
  path: '/entregadores',
  getParentRoute: () => rootRouteImport,
} as any)
const EstabelecimentosRoute = EstabelecimentosRouteImport.update({
  id: '/estabelecimentos',
  path: '/estabelecimentos',
  getParentRoute: () => rootRouteImport,
} as any)
const SuporteRoute = SuporteRouteImport.update({
  id: '/suporte',
  path: '/suporte',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/entregadores': typeof EntregadoresRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/entregadores': typeof EntregadoresRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-funciona': typeof ComoFuncionaRoute
  '/entregadores': typeof EntregadoresRoute
  '/estabelecimentos': typeof EstabelecimentosRoute
  '/suporte': typeof SuporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/como-funciona' | '/entregadores' | '/estabelecimentos' | '/suporte'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/como-funciona' | '/entregadores' | '/estabelecimentos' | '/suporte'
  id:
    | '__root__'
    | '/'
    | '/como-funciona'
    | '/entregadores'
    | '/estabelecimentos'
    | '/suporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoFuncionaRoute: typeof ComoFuncionaRoute
  EntregadoresRoute: typeof EntregadoresRoute
  EstabelecimentosRoute: typeof EstabelecimentosRoute
  SuporteRoute: typeof SuporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-funciona': {
      id: '/como-funciona'
      path: '/como-funciona'
      fullPath: '/como-funciona'
      preLoaderRoute: typeof ComoFuncionaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entregadores': {
      id: '/entregadores'
      path: '/entregadores'
      fullPath: '/entregadores'
      preLoaderRoute: typeof EntregadoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estabelecimentos': {
      id: '/estabelecimentos'
      path: '/estabelecimentos'
      fullPath: '/estabelecimentos'
      preLoaderRoute: typeof EstabelecimentosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suporte': {
      id: '/suporte'
      path: '/suporte'
      fullPath: '/suporte'
      preLoaderRoute: typeof SuporteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoFuncionaRoute: ComoFuncionaRoute,
  EntregadoresRoute: EntregadoresRoute,
  EstabelecimentosRoute: EstabelecimentosRoute,
  SuporteRoute: SuporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
